version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    ports:
      - "3000:3000"
    container_name: nextjs-app
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src/app
      - ~/.gitconfig:/etc/gitconfig
        # command: /bin/sh -c 'npm run dev'
